# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Advertise-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Advertise-iOS
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'RxDataSources'

  target 'Advertise-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Advertise-iOSUITests' do
    # Pods for testing
  end

end
